package main

import (
	"log"
	"math/rand"
)

func (b *Board) AddPatternFromString(offsetx, offsety int, pattern string) {
	var x, y int
	for _, c := range pattern {
		x++
		switch c {
		case '\n':
			x = 0
			y++
		case 'O':
			b.Set(x+offsetx, y+offsety, true)
		}
	}
}

func (b *Board) AddRandom(int, int) *Board {
	for y, l := range b.elements {
		for x := range l {
			//  rand.Seed(time.Now().UnixNano())
			b.Set(x, y, rand.Intn(2) == 1)
		}
	}
	return b
}

func (b *Board) AddBeehive(x, y int) *Board {
	if b.dimx-x < 2 || b.dimy-y < 2 {
		log.Fatal("Dimensions need to be 5,6 at least.")
	}

	coords := [][]int{{1, 0},
		{0, 1}, {2, 1},
		{0, 2}, {2, 2},
		{1, 3}}
	for _, c := range coords {
		b.Set(x+c[0], y+c[1], true)
	}

	return b
}

func (b *Board) AddBlinker(x, y int) *Board {
	if b.dimx-x < 5 || b.dimy-y < 5 {
		log.Fatal("Dimensions need to be 5,5 at least.")
	}

	coords := [][]int{{2, 3}, {3, 3}, {4, 3}}
	for _, c := range coords {
		b.Set(x+c[0], y+c[1], true)
	}

	return b
}

func (b *Board) AddGlider(x, y int) *Board {
	if b.dimx+x < 2 || b.dimy+y < 2 {
		log.Fatal("Dimensions need to be 10,10 at least.")
	}

	coords := [][]int{{0, 1}, {1, 2}, {2, 0}, {2, 1}, {2, 2}}
	for _, c := range coords {
		b.Set(x+c[0], y+c[1], true)
	}

	return b
}

func (b *Board) AddGliderGun(x, y int) *Board {
	pattern := `........................O...........
......................O.O...........
............OO......OO............OO
...........O...O....OO............OO
OO........O.....O...OO..............
OO........O...O.OO....O.O...........
..........O.....O.......O...........
...........O...O....................
............OO......................`
	b.AddPatternFromString(x, y, pattern)
	return b
}

func (b *Board) AddGliderGun2(x, y int) *Board {
	pattern := `............................O..........
............................O.O........
...........OO..................OO......
.........O...O.................OO....OO
...OO...O.....O................OO....OO
...OO..OO.O...O.............O.O........
........O.....O.............O..........
.........O...O.........................
...........OO..........................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
.......................................
..........O.O..........................
.........O..O...OO.....................
OO......OO.....OOO.OO..OO..............
OO....OO...O...O...O...O.O.............
........OO.....O.O........O............
.........O..O..OO......O..O............
..........O.O.............O............
.......................O.O.......OO....
.......................OO........O.O...
...................................O...
...................................OO..`
	b.AddPatternFromString(x, y, pattern)
	return b
}

func (b *Board) AddReflector(x, y int) *Board {
	pattern := `........O
......OOO
.....O...
.....OO..
.........
.........
.........
.........
.........
.........
.........
OO.O.OO..
.........
O.....O..
.........
.OO.OO...
...O.....
.........
.........
.........
.........
...OO....
...OO....`
	b.AddPatternFromString(x, y, pattern)
	return b
}

func (b *Board) AddSuicide(x, y int) *Board {
	pattern := `.........
...OOO...
...O.O...
...O.O...
.........
...O.O...
...O.O...
...OOO...
.........`
	b.AddPatternFromString(x, y, pattern)
	return b
}

func (b *Board) AddFPentomino(x, y int) *Board {
	pattern := `.....
..OO.
.OO..
..O..
.....`
	b.AddPatternFromString(x, y, pattern)
	return b
}
